
<div class="alert alert-warning" role="alert">

    <span class="fa fa-warning" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;

    <label style="display: inline-block; margin-right: 50px"><input type="checkbox" checked="checked" id="autoopen" style="vertical-align: baseline">&nbsp; Editar datos comodamente</label>

</div>
<div class="zf-table-wrap  form-inline">
    <div class="table-header clearfix">
            <div class="col-sm-6 pull-left">
                <?php if($this->name): ?>
                    <header>
                        <h4><?= $this->name ?></h4>
                    </header>
                <?php endif;?>
            </div>
            <?php if ($this->showQuickSearch || $this->showItemPerPage): ?>

                <div class="DT-lf-right">

                    <?php if ($this->showItemPerPage): ?>
                    <div class="DT-per-page">
                        <div class="dataTables_length" id="jq-datatables-example_length">
                            <label> Por página:
                                <select class="itemPerPage form-control">
                                    <?php foreach ($this->itemCountPerPageValues as $item): ?>
                                        <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                                        <option <?php echo $selected ?>><?php echo $item ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </label>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->showQuickSearch): ?>

                        <div class="DT-search">
                            <div id="dataTable_filter" class="dataTables_filter"><label>
                                    <input placeholder="Buscar..." type="text" aria-controls="dataTable" class="quick-search form-control input-sm" value="<?php echo $this->quickSearch ?>">
                                    </label>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>


            <?php endif; ?>
    </div>

    <?php
    $paginator = $this->paginatorClass;



    /**
     * @var \Zend\Paginator\Paginator $paginator
     */

//    \Nette\Diagnostics\Debugger::dump($paginator->getCurrentItemCount());return;
    $firstNumber = ($paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage(), $paginator->getCurrentPageNumber()) - $paginator->getItemCountPerPage() + 1);

    ?>
    <div  class="table-responsive">
    <?php echo $this->table; ?>
    </div>
    <div class="table-footer clearfix text-center">
        <div class="DT-label">
            <div class="dataTables_info" id="jq-datatables-example_info" role="alert" aria-live="polite"
                 aria-relevant="all">Viendo <?php echo $firstNumber ?> a <?php echo ($firstNumber + $paginator->getCurrentItemCount() - 1) ?> de <?php echo $paginator->getTotalItemCount() ?> registros
            </div>
        </div>

        <?php if($this->showExportToCSV): ?>
            <a href="#" class="export-csv btn btn-success">Exportar a CSV</a>
        <?php endif;?>

        <?php if ($this->showPagination): ?>
        <div class="DT-pagination">
            <div class="dataTables_paginate paging_bootstrap pagination">
                <?php echo $this->paginator; ?>
            </div>
        </div>
        <?php endif; ?>

        <div class="processing">

    </div>

    <?php echo $this->paramsWrap; ?>
</div>
